apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  name: {{ include "shared-tokens.name" . -}}- {{- .Values.global.env }}
  labels:
    replication-type: automatic
spec:
  replication:
    automatic: true
---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecretVersion
metadata:
  name: {{ include "shared-tokens.name" . -}}- {{- .Values.global.env }}-version
spec:
  enabled: true
  secretData:
    valueFrom:
      secretKeyRef:
        key: SERVICE_WORKER_TOKEN
        name: {{ include "shared-tokens.name" . }}
  secretRef:
    name: {{ include "shared-tokens.name" . -}}- {{- .Values.global.env }}
