@startuml
hide stereotype
hide circle
!include ../../../../style/default.iuml

package "label_manager" {
  entity "**label-manager-sites**" [[label_manager_label-manager-sites.puml]] {}
}

hide empty fields
hide empty methods

@enduml