@startuml
hide circle
!include ../../../../style/default.iuml

entity "**pick_zone**" [[isps_pick_zone.puml]] {
  + ""pick_zone_id"": //integer [PK]//
  --
  *""pick_zone_code"": //character varying(32)//
  *""pick_zone_created_at"": //timestamp with time zone//
  *""pick_zone_created_by"": //character varying(64)//
  *""pick_zone_desc"": //character varying(512)//
  *""pick_zone_last_modified_at"": //timestamp with time zone//
  *""pick_zone_last_modified_by"": //character varying(64)//
  *""pick_zone_name"": //character varying(64)//
}

@enduml