@startuml
hide circle
!include ../../../../style/default.iuml

entity "**reserved_line_items**" [[oms_reserved_line_items.puml]] {
  + ""id"": //bigint [PK]//
  --
  *""address"": //text//
  *""creation_datetime"": //timestamp with time zone//
  *""line_id"": //bigint [FK]//
  *""quantity"": //bigint//
  *""takeoff_item_id"": //text//
}

@enduml