@startuml
hide stereotype
hide circle
!include ../../../../style/default.iuml

package "bifrost" {
  entity "**ragtime_migrations**" [[bifrost_ragtime_migrations.puml]] {}
}

hide empty fields
hide empty methods

@enduml