@startuml
hide stereotype
hide circle
!include ../../../../style/default.iuml

package "takeoff_mobile_firebase_performance" {
  entity "**com_takeoff_mobileapp_ANDROID**" [[takeoff_mobile_firebase_performance_com_takeoff_mobileapp_ANDROID.puml]] {}
}

hide empty fields
hide empty methods

@enduml