@startuml
hide circle
!include ../../../../style/default.iuml

entity "**com_takeoff_mobileapp_ANDROID**" [[takeoff_mobile_crashlytics_com_takeoff_mobileapp_ANDROID.puml]] {
  --
  *""platform"": //string//
  *""bundle_identifier"": //string//
  *""event_id"": //string//
  *""is_fatal"": //bool//
  *""issue_id"": //string//
  *""issue_title"": //string//
  *""issue_subtitle"": //string//
  *""event_timestamp"": //timestamp [partitioned]//
  *""received_timestamp"": //timestamp//
  *""device"": //struct<manufacturer string, model string, architecture string>//
  *""device"": //struct<manufacturer string, model string, architecture string>//
  *""device"": //struct<manufacturer string, model string, architecture string>//
  *""device"": //struct<manufacturer string, model string, architecture string>//
  *""memory"": //struct<used int64, free int64>//
  *""memory"": //struct<used int64, free int64>//
  *""memory"": //struct<used int64, free int64>//
  *""storage"": //struct<used int64, free int64>//
  *""storage"": //struct<used int64, free int64>//
  *""storage"": //struct<used int64, free int64>//
  *""operating_system"": //struct<display_version string, name string, modification_state string, type string, device_type string>//
  *""operating_system"": //struct<display_version string, name string, modification_state string, type string, device_type string>//
  *""operating_system"": //struct<display_version string, name string, modification_state string, type string, device_type string>//
  *""operating_system"": //struct<display_version string, name string, modification_state string, type string, device_type string>//
  *""operating_system"": //struct<display_version string, name string, modification_state string, type string, device_type string>//
  *""operating_system"": //struct<display_version string, name string, modification_state string, type string, device_type string>//
  *""application"": //struct<build_version string, display_version string>//
  *""application"": //struct<build_version string, display_version string>//
  *""application"": //struct<build_version string, display_version string>//
  *""user"": //struct<name string, email string, id string>//
  *""user"": //struct<name string, email string, id string>//
  *""user"": //struct<name string, email string, id string>//
  *""user"": //struct<name string, email string, id string>//
  *""custom_keys"": //array<struct<key string, value string>>//
  *""custom_keys"": //array<struct<key string, value string>>//
  *""custom_keys"": //array<struct<key string, value string>>//
  *""installation_uuid"": //string//
  *""crashlytics_sdk_version"": //string//
  *""app_orientation"": //string//
  *""device_orientation"": //string//
  *""process_state"": //string//
  *""logs"": //array<struct<timestamp timestamp, message string>>//
  *""logs"": //array<struct<timestamp timestamp, message string>>//
  *""logs"": //array<struct<timestamp timestamp, message string>>//
  *""breadcrumbs"": //array<struct<timestamp timestamp, name string, params array<struct<key string, value string>>>>//
  *""breadcrumbs"": //array<struct<timestamp timestamp, name string, params array<struct<key string, value string>>>>//
  *""breadcrumbs"": //array<struct<timestamp timestamp, name string, params array<struct<key string, value string>>>>//
  *""breadcrumbs"": //array<struct<timestamp timestamp, name string, params array<struct<key string, value string>>>>//
  *""breadcrumbs"": //array<struct<timestamp timestamp, name string, params array<struct<key string, value string>>>>//
  *""breadcrumbs"": //array<struct<timestamp timestamp, name string, params array<struct<key string, value string>>>>//
  *""blame_frame"": //struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>//
  *""blame_frame"": //struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>//
  *""blame_frame"": //struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>//
  *""blame_frame"": //struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>//
  *""blame_frame"": //struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>//
  *""blame_frame"": //struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>//
  *""blame_frame"": //struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>//
  *""blame_frame"": //struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>//
  *""blame_frame"": //struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>//
  *""exceptions"": //array<struct<type string, exception_message string, nested bool, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""exceptions"": //array<struct<type string, exception_message string, nested bool, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""exceptions"": //array<struct<type string, exception_message string, nested bool, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""exceptions"": //array<struct<type string, exception_message string, nested bool, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""exceptions"": //array<struct<type string, exception_message string, nested bool, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""exceptions"": //array<struct<type string, exception_message string, nested bool, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""exceptions"": //array<struct<type string, exception_message string, nested bool, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""exceptions"": //array<struct<type string, exception_message string, nested bool, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""exceptions"": //array<struct<type string, exception_message string, nested bool, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""exceptions"": //array<struct<type string, exception_message string, nested bool, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""exceptions"": //array<struct<type string, exception_message string, nested bool, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""exceptions"": //array<struct<type string, exception_message string, nested bool, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""exceptions"": //array<struct<type string, exception_message string, nested bool, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""exceptions"": //array<struct<type string, exception_message string, nested bool, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""exceptions"": //array<struct<type string, exception_message string, nested bool, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""exceptions"": //array<struct<type string, exception_message string, nested bool, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""errors"": //array<struct<queue_name string, code int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""errors"": //array<struct<queue_name string, code int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""errors"": //array<struct<queue_name string, code int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""errors"": //array<struct<queue_name string, code int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""errors"": //array<struct<queue_name string, code int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""errors"": //array<struct<queue_name string, code int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""errors"": //array<struct<queue_name string, code int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""errors"": //array<struct<queue_name string, code int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""errors"": //array<struct<queue_name string, code int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""errors"": //array<struct<queue_name string, code int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""errors"": //array<struct<queue_name string, code int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""errors"": //array<struct<queue_name string, code int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""errors"": //array<struct<queue_name string, code int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""errors"": //array<struct<queue_name string, code int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""errors"": //array<struct<queue_name string, code int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""threads"": //array<struct<crashed bool, thread_name string, queue_name string, signal_name string, signal_code string, crash_address int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""threads"": //array<struct<crashed bool, thread_name string, queue_name string, signal_name string, signal_code string, crash_address int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""threads"": //array<struct<crashed bool, thread_name string, queue_name string, signal_name string, signal_code string, crash_address int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""threads"": //array<struct<crashed bool, thread_name string, queue_name string, signal_name string, signal_code string, crash_address int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""threads"": //array<struct<crashed bool, thread_name string, queue_name string, signal_name string, signal_code string, crash_address int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""threads"": //array<struct<crashed bool, thread_name string, queue_name string, signal_name string, signal_code string, crash_address int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""threads"": //array<struct<crashed bool, thread_name string, queue_name string, signal_name string, signal_code string, crash_address int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""threads"": //array<struct<crashed bool, thread_name string, queue_name string, signal_name string, signal_code string, crash_address int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""threads"": //array<struct<crashed bool, thread_name string, queue_name string, signal_name string, signal_code string, crash_address int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""threads"": //array<struct<crashed bool, thread_name string, queue_name string, signal_name string, signal_code string, crash_address int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""threads"": //array<struct<crashed bool, thread_name string, queue_name string, signal_name string, signal_code string, crash_address int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""threads"": //array<struct<crashed bool, thread_name string, queue_name string, signal_name string, signal_code string, crash_address int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""threads"": //array<struct<crashed bool, thread_name string, queue_name string, signal_name string, signal_code string, crash_address int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""threads"": //array<struct<crashed bool, thread_name string, queue_name string, signal_name string, signal_code string, crash_address int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""threads"": //array<struct<crashed bool, thread_name string, queue_name string, signal_name string, signal_code string, crash_address int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""threads"": //array<struct<crashed bool, thread_name string, queue_name string, signal_name string, signal_code string, crash_address int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""threads"": //array<struct<crashed bool, thread_name string, queue_name string, signal_name string, signal_code string, crash_address int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""threads"": //array<struct<crashed bool, thread_name string, queue_name string, signal_name string, signal_code string, crash_address int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""threads"": //array<struct<crashed bool, thread_name string, queue_name string, signal_name string, signal_code string, crash_address int64, title string, subtitle string, blamed bool, frames array<struct<line int64, file string, symbol string, offset int64, address int64, library string, owner string, blamed bool>>>>//
  *""error_type"": //string//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""unity_metadata"": //struct<unity_version string, debug_build bool, processor_type string, processor_count int64, processor_frequency int64, system_memory_size int64, graphics_memory_size int64, graphics_device_id int64, graphics_device_vendor_id int64, graphics_device_name string, graphics_device_vendor string, graphics_device_version string, graphics_device_type string, graphics_shader_level int64, graphics_render_target_count int64, graphics_copy_texture_support string, graphics_max_texture_size int64, screen_size string, screen_dpi float64, screen_refresh_rate int64, processor_frequency_mhz int64, system_memory_size_mb int64, graphics_memory_size_mb int64, screen_size_px string, screen_refresh_rate_hz int64, screen_resolution_dpi string>//
  *""variant_id"": //string//
}

@enduml