@startuml
hide circle
!include ../../../../style/default.iuml

entity "**ce_activity**" [[sonarqube_ce_activity.puml]] {
  + ""uuid"": //character varying(40) [PK]//
  --
  *""analysis_uuid"": //character varying(50)//
  *""component_uuid"": //character varying(40)//
  *""created_at"": //bigint//
  *""error_message"": //character varying(1000)//
  *""error_stacktrace"": //text//
  *""error_type"": //character varying(20)//
  *""executed_at"": //bigint//
  *""execution_count"": //integer//
  *""execution_time_ms"": //bigint//
  *""is_last"": //boolean//
  *""is_last_key"": //character varying(55)//
  *""main_component_uuid"": //character varying(40)//
  *""main_is_last"": //boolean//
  *""main_is_last_key"": //character varying(55)//
  *""started_at"": //bigint//
  *""status"": //character varying(15)//
  *""submitted_at"": //bigint//
  *""submitter_uuid"": //character varying(255)//
  *""task_type"": //character varying(15)//
  *""updated_at"": //bigint//
  *""worker_uuid"": //character varying(40)//
}

@enduml