@startuml
hide circle
!include ../../../../style/default.iuml

entity "**organization_members**" [[sonarqube_organization_members.puml]] {
  + ""organization_uuid"": //character varying(40) [PK]//
  + ""user_uuid"": //character varying(255) [PK]//
  --
}

@enduml