@startuml
hide circle
!include ../../../../style/default.iuml

entity "**alm_pats**" [[sonarqube_alm_pats.puml]] {
  + ""uuid"": //character varying(40) [PK]//
  --
  *""alm_setting_uuid"": //character varying(40)//
  *""created_at"": //bigint//
  *""pat"": //character varying(2000)//
  *""updated_at"": //bigint//
  *""user_uuid"": //character varying(256)//
}

@enduml