@startuml
hide circle
!include ../../../../style/default.iuml

entity "**notifications**" [[sonarqube_notifications.puml]] {
  + ""uuid"": //character varying(40) [PK]//
  --
  *""created_at"": //bigint//
  *""data"": //bytea//
}

@enduml