@startuml
hide circle
!include ../../../../style/default.iuml

entity "**perm_templates_groups**" [[sonarqube_perm_templates_groups.puml]] {
  + ""uuid"": //character varying(40) [PK]//
  --
  *""created_at"": //timestamp without time zone//
  *""group_uuid"": //character varying(40)//
  *""permission_reference"": //character varying(64)//
  *""template_uuid"": //character varying(40)//
  *""updated_at"": //timestamp without time zone//
}

@enduml