common: # common values for s3 environments across all retailers
  LAUNCHDARKLY_SDK_KEY: c2RrLWZiY2U2OWZmLWFhMTAtNDQ0Yy1iMTY2LWMzMDI0OWY3OTlmNA==
  LAUNCHDARKLY_CLIENT_SDK_KEY: NWQ5MzgzYWQ4YTY1MjAwODljZjcxOThi
