@startuml
hide stereotype
hide circle
!include ../../../../style/default.iuml

package "service_catalog" {
  !include service_catalog_migrations_data_abs.puml
  !include service_catalog_migrations_data_common.puml
  !include service_catalog_migrations_schema_common.puml
  !include service_catalog_op_address.puml
  !include service_catalog_op_address_l1_aisles.puml
  !include service_catalog_op_address_l2_bays.puml
  !include service_catalog_op_config_definition_version.puml
  !include service_catalog_op_config_items.puml
  !include service_catalog_op_flow_racks.puml
  !include service_catalog_op_location_ip_address_printers.puml
  !include service_catalog_op_location_ip_addresses_ranges.puml
  !include service_catalog_op_location_tote_types.puml
  !include service_catalog_op_locations.puml
  !include service_catalog_op_measure_units.puml
  !include service_catalog_op_osrs.puml
  !include service_catalog_op_planograms.puml
  !include service_catalog_op_printers.puml
  !include service_catalog_op_printing_nodes.puml
  !include service_catalog_op_product_category_limits.puml
  !include service_catalog_op_routes.puml
  !include service_catalog_op_staging_configs.puml
  !include service_catalog_op_staging_locations.puml
  !include service_catalog_op_tote_cell_dimensions.puml
  !include service_catalog_op_tote_types.puml
  !include service_catalog_op_tote_types_v2.puml
  !include service_catalog_sd_area_types.puml
  !include service_catalog_sd_areas.puml
  !include service_catalog_sd_barcode_formats.puml
  !include service_catalog_sd_config_categories.puml
  !include service_catalog_sd_config_item_categories.puml
  !include service_catalog_sd_config_item_definitions.puml
  !include service_catalog_sd_config_item_level.puml
  !include service_catalog_sd_countries.puml
  !include service_catalog_sd_data_types.puml
  !include service_catalog_sd_ip_address_purposes.puml
  !include service_catalog_sd_location_types.puml
  !include service_catalog_sd_measure_types.puml
  !include service_catalog_sd_measure_unit_definitions.puml
  !include service_catalog_sd_media_types.puml
  !include service_catalog_sd_movable_asset_types.puml
  !include service_catalog_sd_number_sides.puml
  !include service_catalog_sd_osr_container_types.puml
  !include service_catalog_sd_paper_sizes.puml
  !include service_catalog_sd_paper_sizes_per_printer_models.puml
  !include service_catalog_sd_paper_types.puml
  !include service_catalog_sd_paper_types_per_printer_models.puml
  !include service_catalog_sd_printer_models.puml
  !include service_catalog_sd_printing_methods.puml
  !include service_catalog_sd_states.puml
  !include service_catalog_sd_static_dynamic_types.puml
  !include service_catalog_sd_temperature_zones.puml
  !include service_catalog_sd_tote_kinds.puml
  !include service_catalog_sd_tote_slot_definitions.puml
}
"**op_address**" -- "**sd_areas**"
"**op_address**" -- "**op_address_l2_bays**"
"**op_address**" -- "**op_locations**"
"**op_address_l2_bays**" -- "**op_address_l1_aisles**"
"**op_config_items**" -- "**sd_config_item_definitions**"
"**op_config_items**" -- "**op_locations**"
"**op_flow_racks**" -- "**op_locations**"
"**op_location_ip_address_printers**" -- "**sd_ip_address_purposes**"
"**op_location_ip_address_printers**" -- "**op_locations**"
"**op_location_ip_addresses_ranges**" -- "**sd_ip_address_purposes**"
"**op_location_ip_addresses_ranges**" -- "**op_locations**"
"**op_location_tote_types**" -- "**op_locations**"
"**op_location_tote_types**" -- "**op_tote_types**"
"**op_locations**" -- "**sd_location_types**"
"**op_locations**" -- "**op_locations**"
"**op_locations**" -- "**sd_states**"
"**op_measure_units**" -- "**sd_measure_types**"
"**op_measure_units**" -- "**sd_measure_unit_definitions**"
"**op_osrs**" -- "**op_locations**"
"**op_planograms**" -- "**op_address_l2_bays**"
"**op_planograms**" -- "**op_locations**"
"**op_printers**" -- "**op_locations**"
"**op_printing_nodes**" -- "**op_locations**"
"**op_printing_nodes**" -- "**sd_media_types**"
"**op_product_category_limits**" -- "**op_tote_types**"
"**op_routes**" -- "**op_locations**"
"**op_staging_configs**" -- "**op_routes**"
"**op_staging_configs**" -- "**op_staging_locations**"
"**op_staging_locations**" -- "**op_locations**"
"**op_tote_cell_dimensions**" -- "**op_tote_types**"
"**op_tote_types**" -- "**sd_barcode_formats**"
"**op_tote_types**" -- "**sd_temperature_zones**"
"**op_tote_types**" -- "**sd_tote_kinds**"
"**op_tote_types_v2**" -- "**sd_barcode_formats**"
"**op_tote_types_v2**" -- "**op_locations**"
"**op_tote_types_v2**" -- "**sd_temperature_zones**"
"**op_tote_types_v2**" -- "**sd_tote_kinds**"
"**sd_areas**" -- "**sd_area_types**"
"**sd_areas**" -- "**sd_temperature_zones**"
"**sd_config_item_categories**" -- "**sd_config_categories**"
"**sd_config_item_categories**" -- "**sd_config_item_definitions**"
"**sd_config_item_definitions**" -- "**sd_config_item_level**"
"**sd_config_item_definitions**" -- "**sd_measure_types**"
"**sd_config_item_definitions**" -- "**sd_data_types**"
"**sd_measure_unit_definitions**" -- "**sd_measure_types**"
"**sd_paper_sizes_per_printer_models**" -- "**sd_paper_sizes**"
"**sd_paper_sizes_per_printer_models**" -- "**sd_printer_models**"
"**sd_paper_types**" -- "**sd_paper_sizes**"
"**sd_paper_types**" -- "**sd_printing_methods**"
"**sd_paper_types_per_printer_models**" -- "**sd_paper_types**"
"**sd_paper_types_per_printer_models**" -- "**sd_printer_models**"
"**sd_states**" -- "**sd_countries**"

@enduml