@startuml
hide circle
!include ../../../../style/default.iuml

entity "**git_pull_requests**" [[calyx_git_pull_requests.puml]] {
  + ""git_pr_number"": //integer [PK]//
  + ""git_repo"": //character varying(100) [PK]//
  --
  *""created"": //timestamp with time zone//
  *""merge_commit_oid"": //character varying(40)//
}

@enduml