@startuml
hide circle
!include ../../../../style/default.iuml

entity "**sd_data_types**" [[service_catalog_sd_data_types.puml]] {
  + ""type_id"": //bigint [PK]//
  --
  *""type_name"": //character varying(16)//
}

@enduml