@startuml
hide circle
!include ../../../../style/default.iuml

entity "**op_tote_cell_dimensions**" [[service_catalog_op_tote_cell_dimensions.puml]] {
  + ""tote_cells_type_id"": //bigint [PK]//
  --
  *""single_cell_height"": //numeric(10,4)//
  *""single_cell_length"": //numeric(10,4)//
  *""single_cell_width"": //numeric(10,4)//
  *""tote_cells_max_quantity"": //bigint//
  *""tote_type_id"": //bigint [FK]//
}

@enduml