@startuml
hide circle
!include ../../../../style/default.iuml

entity "**sd_tote_kinds**" [[service_catalog_sd_tote_kinds.puml]] {
  + ""tote_kind_id"": //bigint [PK]//
  --
  *""tote_kind_name"": //character varying//
}

@enduml