@startuml
hide circle
!include ../../../../style/default.iuml

entity "**migrations_data_abs**" [[service_catalog_migrations_data_abs.puml]] {
  --
  *""created_at"": //character varying(32)//
  *""id"": //character varying(255)//
}

@enduml