@startuml
hide circle
!include ../../../../style/default.iuml

entity "**sd_static_dynamic_types**" [[service_catalog_sd_static_dynamic_types.puml]] {
  + ""address_type_id"": //bigint [PK]//
  --
  *""address_type_name"": //text//
}

@enduml