@startuml
hide circle
!include ../../../../style/default.iuml

entity "**ragtime_migrations**" [[cc_ragtime_migrations.puml]] {
  --
  *""created_at"": //character varying(32)//
  *""id"": //character varying(255)//
}

@enduml