auth-service:
  helm_chart_version: 23-03-17.219
bifrost:
  helm_chart_version: 23-03-17.148
cartonization:
  helm_chart_version: 23-03-14.105
decanting-service:
  helm_chart_version: 23-03-21.18
distiller:
  image: 23-03-20.218.1
  helm_chart_version: 23-03-22.125.1
ims:
  image: 23-02-09.7
  helm_chart_version: 23-03-02.264
integration:
  helm_chart_version: 23-03-01.65
platform:
  helm_chart_version: 23-03-17.683
service-catalog:
  helm_chart_version: 23-03-17.273
