- categories:
  - isps
  location-code-tom: 0068
  name: ISPS_CONFIGURATION
  value: '[{"preliminary":"10:00","cutoffs":["11:50"]},{"preliminary":"12:00","cutoffs":["13:50"]},{"delta":"11:00","cutoffs":["11:50"]},{"delta":"13:00","cutoffs":["13:50"]}]'
  value-type: string
- categories:
    - pickerman
    - isps
  location-code-tom: "0068"
  name: ISPS_ENABLED
  value: true
  value-type: boolean
