auth-service:
  helm_chart_version: 22-01-24.168
bifrost:
  helm_chart_version: 21-12-08.113-hotfix.0
cartonization:
  helm_chart_version: 22-01-21.74
decanting-service:
  helm_chart_version: 22-01-17.324-hotfix.0
distiller:
  image: 22-01-21.352
  helm_chart_version: 22-01-21.174-hotfix.3
ims:
  image: 22-01-14.102
  helm_chart_version: 22-01-14.203
integration:
  helm_chart_version: 22-01-19.927
isps:
  helm_chart_version: 22-01-11.140-hotfix.0
oms:
  helm_chart_version: 22-01-26.397
osr-emulator:
  helm_chart_version: 22-01-18.171
pickerman:
  helm_chart_version: 22-01-31.105
platform:
  helm_chart_version: 22-01-26.440-hotfix.1
service-catalog:
  helm_chart_version: 21-12-20.230
