- categories:
    - osr
  name: OSR_WEIGHT_VARIABLE_ITEM_ENABLED
  value: true
  location-code-tom: '9999'
  value-type: boolean
- categories:
    - osr
  name: capacity_data_mode
  value: 'PUBSUB'
  location-code-tom: '9999'
  value-type: string
- categories:
    - osr
  name: dispatch_error_ramp
  value: 'DISPATCH99'
  location-code-tom: '9999'
  value-type: string
- categories:
    - osr
  name: dispatch_ramp_count
  value: 5
  location-code-tom: '9999'
  value-type: integer
- categories:
    - osr
  name: dispatch_ramp_depth
  value: 4
  location-code-tom: '9999'
  value-type: integer
- categories:
    - osr
  name: dispatch_ramp_id_gen
  value: 'DISPATCH%02d'
  location-code-tom: '9999'
  value-type: string
- categories:
    - osr
  name: dispatch_start_ramp
  value: 1
  location-code-tom: '9999'
  value-type: integer
- categories:
    - osr
  name: osr_ftp_host
  value: 'tgim-ftp'
  location-code-tom: '9999'
  value-type: string
- categories:
    - osr
  name: osr_ftp_passive_mode
  value: true
  location-code-tom: '9999'
  value-type: boolean
- categories:
    - osr
  name: osr_ftp_password
  value: 'k1705kch'
  location-code-tom: '9999'
  value-type: string
- categories:
    - osr
  name: osr_ftp_port
  value: 21
  location-code-tom: '9999'
  value-type: integer
- categories:
    - osr
  name: osr_ftp_protocol
  value: 'ftp'
  location-code-tom: '9999'
  value-type: string
- categories:
    - osr
  name: osr_ftp_username
  value: 'k1705kch_1'
  location-code-tom: '9999'
  value-type: string
- categories:
    - osr
  name: send_mrsl_to_kisoft
  value: true
  location-code-tom: '9999'
  value-type: boolean
- categories:
    - outbound
  name: has_osr
  value: true
  location-code-tom: '9999'
  value-type: boolean
- categories:
  - decanting
  location-code-tom: '9999'
  name: approx_long_divider_weight
  value: 0.837757
  value-type: numeric
- categories:
  - decanting
  location-code-tom: '9999'
  name: approx_short_divider_weight
  value: 0.529109
  value-type: numeric
- categories:
  - decanting
  location-code-tom: '9999'
  name: approx_source_tote_weight
  value: 6.684416
  value-type: numeric
- categories:
  - decanting
  location-code-tom: '9999'
  name: decanting_safety_net_percentage
  value: 3
  value-type: integer
- categories:
  - decanting-ui
  location-code-tom: '9999'
  name: DECANTING_UI_OSR_WEIGHT_VARIABLE_ITEM_ENABLED
  value: true
  value-type: boolean
- categories:
  - decanting-ui
  location-code-tom: null
  name: DECANTING_UI_APPROX_LONG_DIVIDER_WEIGHT
  value: 0.837757
  value-type: numeric
- categories:
  - decanting-ui
  location-code-tom: null
  name: DECANTING_UI_APPROX_SHORT_DIVIDER_WEIGHT
  value: 0.529109
  value-type: numeric
- categories:
  - decanting-ui
  location-code-tom: null
  name: DECANTING_UI_APPROX_SOURCE_TOTE_WEIGHT
  value: 6.684416
  value-type: numeric
- categories:
  - decanting-ui
  location-code-tom: null
  name: DECANTING_UI_DEFAULT_ADD_TO_TOTE_QUANTITY
  value: 0
  value-type: integer
- categories:
  - decanting-ui
  location-code-tom: null
  name: DECANTING_UI_DISABLE_PROCEED_ON_OVERWEIGHT_TOTE
  value: false
  value-type: boolean
- categories:
  - decanting-ui
  location-code-tom: null
  name: DECANTING_UI_DISPLAY_INTERNATIONAL_DATE_FORMAT
  value: false
  value-type: boolean
- categories:
  - decanting-ui
  location-code-tom: null
  name: DECANTING_UI_DISPLAY_OVERWEIGHT_WARNING_AS_MODAL
  value: true
  value-type: boolean
- categories:
  - decanting-ui
  location-code-tom: null
  name: DECANTING_UI_EARLIEST_VALID_EXPIRATION_DATE
  value: 2
  value-type: integer
- categories:
  - decanting-ui
  location-code-tom: null
  name: DECANTING_UI_EMAIL_DOMAIN
  value: <domain_name>
  value-type: string
- categories:
  - decanting-ui
  location-code-tom: null
  name: DECANTING_UI_ENABLE_EIGHT_SLOT_TOTES
  value: true
  value-type: boolean
- categories:
  - decanting-ui
  location-code-tom: null
  name: DECANTING_UI_ENABLE_IN_STORE_TRANSFER
  value: true
  value-type: boolean
- categories:
  - decanting-ui
  location-code-tom: null
  name: DECANTING_UI_IDLE_TIME_OUT
  value: 300000
  value-type: integer
- categories:
  - decanting-ui
  location-code-tom: null
  name: DECANTING_UI_INITIAL_TOTE_SLOT_COUNT
  value: 4
  value-type: integer
- categories:
  - decanting-ui
  location-code-tom: null
  name: DECANTING_UI_OSR_CAPACITY_DANGER_AMOUNT
  value: 1
  value-type: integer
- categories:
  - decanting-ui
  location-code-tom: null
  name: DECANTING_UI_OSR_CAPACITY_WARNING_AMOUNT
  value: 12
  value-type: integer
- categories:
  - decanting-ui
  location-code-tom: null
  name: DECANTING_UI_PAYLOAD_WEIGHT_CAPACITY
  value: 59.5248
  value-type: numeric
- categories:
  - decanting-ui
  location-code-tom: null
  name: DECANTING_UI_PREVENT_DECANTING_WHEN_OSR_IS_FULL
  value: true
  value-type: boolean
- categories:
  - decanting-ui
  location-code-tom: null
  name: DECANTING_UI_SHOW_TIME_OUT_MODAL_DURATION
  value: 30000
  value-type: integer
