common: # common values for int environments across all retailers
  LAUNCHDARKLY_SDK_KEY: c2RrLWU2MTAzM2MyLTY2NmQtNDJjMi1hNWQ1LWE3YTgzY2U3NGIyMQ==
  LAUNCHDARKLY_CLIENT_SDK_KEY: NWQ5MzU0N2U4YTY1MjAwODljZjcwMzdi
