@startuml
hide stereotype
hide circle
!include ../../../../style/default.iuml

package "metabase" {
  !include metabase_activity.puml
  !include metabase_card_label.puml
  !include metabase_collection.puml
  !include metabase_collection_permission_graph_revision.puml
  !include metabase_computation_job.puml
  !include metabase_computation_job_result.puml
  !include metabase_core_session.puml
  !include metabase_core_user.puml
  !include metabase_dashboard_favorite.puml
  !include metabase_dashboardcard_series.puml
  !include metabase_data_migrations.puml
  !include metabase_databasechangelog.puml
  !include metabase_databasechangeloglock.puml
  !include metabase_dependency.puml
  !include metabase_dimension.puml
  !include metabase_group_table_access_policy.puml
  !include metabase_label.puml
  !include metabase_login_history.puml
  !include metabase_metabase_database.puml
  !include metabase_metabase_field.puml
  !include metabase_metabase_fieldvalues.puml
  !include metabase_metabase_table.puml
  !include metabase_metric.puml
  !include metabase_metric_important_field.puml
  !include metabase_moderation_review.puml
  !include metabase_native_query_snippet.puml
  !include metabase_permissions.puml
  !include metabase_permissions_group.puml
  !include metabase_permissions_group_membership.puml
  !include metabase_permissions_revision.puml
  !include metabase_pulse.puml
  !include metabase_pulse_card.puml
  !include metabase_pulse_channel.puml
  !include metabase_pulse_channel_recipient.puml
  !include metabase_qrtz_blob_triggers.puml
  !include metabase_qrtz_calendars.puml
  !include metabase_qrtz_cron_triggers.puml
  !include metabase_qrtz_fired_triggers.puml
  !include metabase_qrtz_job_details.puml
  !include metabase_qrtz_locks.puml
  !include metabase_qrtz_paused_trigger_grps.puml
  !include metabase_qrtz_scheduler_state.puml
  !include metabase_qrtz_simple_triggers.puml
  !include metabase_qrtz_simprop_triggers.puml
  !include metabase_qrtz_triggers.puml
  !include metabase_query.puml
  !include metabase_query_cache.puml
  !include metabase_query_execution.puml
  !include metabase_report_card.puml
  !include metabase_report_cardfavorite.puml
  !include metabase_report_dashboard.puml
  !include metabase_report_dashboardcard.puml
  !include metabase_revision.puml
  !include metabase_secret.puml
  !include metabase_segment.puml
  !include metabase_setting.puml
  !include metabase_task_history.puml
  !include metabase_view_log.puml
}
"**activity**" -- "**core_user**"
"**card_label**" -- "**report_card**"
"**card_label**" -- "**label**"
"**collection**" -- "**core_user**"
"**collection_permission_graph_revision**" -- "**core_user**"
"**computation_job**" -- "**core_user**"
"**computation_job_result**" -- "**computation_job**"
"**core_session**" -- "**core_user**"
"**dashboard_favorite**" -- "**report_dashboard**"
"**dashboard_favorite**" -- "**core_user**"
"**dashboardcard_series**" -- "**report_card**"
"**dashboardcard_series**" -- "**report_dashboardcard**"
"**dimension**" -- "**metabase_field**"
"**dimension**" -- "**metabase_field**"
"**group_table_access_policy**" -- "**report_card**"
"**group_table_access_policy**" -- "**permissions_group**"
"**group_table_access_policy**" -- "**metabase_table**"
"**login_history**" -- "**core_session**"
"**login_history**" -- "**core_user**"
"**metabase_database**" -- "**core_user**"
"**metabase_field**" -- "**metabase_field**"
"**metabase_field**" -- "**metabase_table**"
"**metabase_fieldvalues**" -- "**metabase_field**"
"**metabase_table**" -- "**metabase_database**"
"**metric**" -- "**core_user**"
"**metric**" -- "**metabase_table**"
"**metric_important_field**" -- "**metabase_field**"
"**metric_important_field**" -- "**metric**"
"**native_query_snippet**" -- "**collection**"
"**native_query_snippet**" -- "**core_user**"
"**permissions**" -- "**permissions_group**"
"**permissions_group_membership**" -- "**permissions_group**"
"**permissions_group_membership**" -- "**core_user**"
"**permissions_revision**" -- "**core_user**"
"**pulse**" -- "**collection**"
"**pulse**" -- "**core_user**"
"**pulse**" -- "**report_dashboard**"
"**pulse_card**" -- "**report_card**"
"**pulse_card**" -- "**report_dashboardcard**"
"**pulse_card**" -- "**pulse**"
"**pulse_channel**" -- "**pulse**"
"**pulse_channel_recipient**" -- "**pulse_channel**"
"**pulse_channel_recipient**" -- "**core_user**"
"**qrtz_blob_triggers**" -- "**qrtz_triggers**"
"**qrtz_cron_triggers**" -- "**qrtz_triggers**"
"**qrtz_simple_triggers**" -- "**qrtz_triggers**"
"**qrtz_simprop_triggers**" -- "**qrtz_triggers**"
"**qrtz_triggers**" -- "**qrtz_job_details**"
"**report_card**" -- "**collection**"
"**report_card**" -- "**core_user**"
"**report_card**" -- "**core_user**"
"**report_card**" -- "**metabase_database**"
"**report_card**" -- "**metabase_table**"
"**report_cardfavorite**" -- "**report_card**"
"**report_cardfavorite**" -- "**core_user**"
"**report_dashboard**" -- "**collection**"
"**report_dashboard**" -- "**core_user**"
"**report_dashboard**" -- "**core_user**"
"**report_dashboardcard**" -- "**report_card**"
"**report_dashboardcard**" -- "**report_dashboard**"
"**revision**" -- "**core_user**"
"**secret**" -- "**core_user**"
"**segment**" -- "**core_user**"
"**segment**" -- "**metabase_table**"
"**view_log**" -- "**core_user**"

@enduml