@startuml
hide circle
!include ../../../../style/default.iuml

entity "**data_migrations**" [[metabase_data_migrations.puml]] {
  + ""id"": //character varying(254) [PK]//
  --
  *""timestamp"": //timestamp without time zone//
}

@enduml