@startuml
hide circle
!include ../../../../style/default.iuml

entity "**qrtz_calendars**" [[metabase_qrtz_calendars.puml]] {
  + ""calendar_name"": //character varying(200) [PK]//
  + ""sched_name"": //character varying(120) [PK]//
  --
  *""calendar"": //bytea//
}

@enduml