@startuml
hide circle
!include ../../../../style/default.iuml

entity "**collection_permission_graph_revision**" [[metabase_collection_permission_graph_revision.puml]] {
  + ""id"": //integer [PK]//
  --
  *""after"": //text//
  *""before"": //text//
  *""created_at"": //timestamp without time zone//
  *""remark"": //text//
  *""user_id"": //integer [FK]//
}

@enduml