@startuml
hide circle
!include ../../../../style/default.iuml

entity "**secret**" [[metabase_secret.puml]] {
  + ""id"": //integer [PK]//
  + ""version"": //integer [PK]//
  --
  *""created_at"": //timestamp with time zone//
  *""creator_id"": //integer [FK]//
  *""kind"": //character varying(254)//
  *""name"": //character varying(254)//
  *""source"": //character varying(254)//
  *""updated_at"": //timestamp with time zone//
  *""value"": //bytea//
}

@enduml