@startuml
hide stereotype
hide circle
!include ../../../../style/default.iuml

package "assortment_management_db" {
  !include assortment_management_db_csvCache.puml
  !include assortment_management_db_recommendationDecision.puml
  !include assortment_management_db_SchemaMigrations.puml
  !include assortment_management_db_setting.puml
}

@enduml