@startuml
hide circle
!include ../../../../style/default.iuml

entity "**setting**" [[assortment_management_db_setting.puml]] {
  + ""retailer"": //STRING(MAX) [PK]//
  + ""mfc_id"": //STRING(MAX) [PK]//
  + ""key"": //STRING(MAX) [PK]//
  --
  *""value"": //STRING(MAX)//
}

@enduml