version: "3.3"

services:

  site:
    platform: linux/arm64/v8
    image: docsy/docsy-example
    build:
      context: .
    command: server
    ports:
      - "1313:1313"
    volumes:
      - .:/src
