# defect https://github.com/gohugoio/hugo/issues/10839
FROM klakegg/hugo:ext-debian

#RUN apk update && apk add git
RUN apt update && apt install git

# RUN apk add --no-cache \
#     gcompat \
#     libc6-compat \
#     ... && \
#     ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2
