@startuml
hide circle
!include ../../../../style/default.iuml

entity "**o**" [[couchdb_o.puml]] {
  + ""_id"": //string [PK]//
  --
  *""acquire.is_processed"": //boolean//
  *""acquire.notifications"": //array//
  *""actual_items_price"": //int//
  *""approach_sms"": //boolean//
  *""arrival_time"": //<unknown>//
  *""attached_files"": //array//
  *""authorization_hold"": //int//
  *""bags_count"": //int//
  *""batch_order_id"": //string//
  *""bonus_sms"": //boolean//
  *""bottle_deposit"": //<unknown>//
  *""boxes"": //array[string]//
  *""boxes_left"": //boolean//
  *""boxes_retrieved"": //boolean//
  *""boxes_retrieved_time"": //<unknown>//
  *""changes"": //array//
  *""chat_id"": //<unknown>//
  *""client_feedback.comment"": //<unknown>//
  *""client_feedback.contact_operator"": //<unknown>//
  *""client_feedback.courier_rating"": //<unknown>//
  *""client_feedback.created"": //datetime//
  *""client_feedback.is_properly_picked"": //<unknown>//
  *""client_feedback.is_properly_picked_date"": //<unknown>//
  *""client_feedback.like_service"": //<unknown>//
  *""client_feedback.operator_rating"": //<unknown>//
  *""client_feedback.overall_rating"": //<unknown>//
  *""client_feedback.picker_rating"": //<unknown>//
  *""client_feedback.quality_grocery_rating"": //<unknown>//
  *""client_feedback.sms_rating"": //<unknown>//
  *""client_feedback.would_recommend_rating"": //<unknown>//
  *""client_feedback_should_send"": //<unknown>//
  *""client_id"": //string//
  *""client_ids_previous"": //array//
  *""client_paid_money"": //int//
  *""comment"": //string//
  *""confirmation_delivery_diff"": //map//
  *""confirmation_sms"": //boolean//
  *""courier_id"": //<unknown>//
  *""created"": //datetime//
  *""delivered"": //<unknown>//
  *""delivered_email_should_send"": //boolean//
  *""delivery_contract_id"": //<unknown>//
  *""delivery_contract_params.contract_id"": //<unknown>//
  *""delivery_contract_params.delivery_price"": //int//
  *""delivery_contract_params.delivery_type"": //string//
  *""delivery_contract_params.dump"": //map//
  *""delivery_contract_params.end_time"": //<unknown>//
  *""delivery_contract_params.location_id"": //datetime//
  *""delivery_contract_params.route_id"": //string//
  *""delivery_contract_params.start_time"": //datetime//
  *""delivery_contract_params.timezone"": //<unknown>//
  *""delivery_contract_params.zone_id"": //datetime//
  *""destination"": //<unknown>//
  *""device_info.device_data"": //string//
  *""device_info.ip_address"": //string//
  *""discounts"": //array//
  *""external_delivery_id"": //<unknown>//
  *""external_delivery_time_window_id"": //<unknown>//
  *""geocoding_status"": //map//
  *""import_data"": //<unknown>//
  *""ip_country"": //<unknown>//
  *""items[].amount"": //int//
  *""items[].avg_weight_unit"": //string//
  *""items[].avg_weight_value"": //float//
  *""items[].base_price"": //int//
  *""items[].comment"": //string//
  *""items[].id"": //string//
  *""items[].is_alcoholic"": //boolean//
  *""items[].is_beer"": //boolean//
  *""items[].is_scalable"": //boolean//
  *""items[].is_weight_variable"": //boolean//
  *""items[].name"": //string//
  *""items[].old_price"": //int//
  *""items[].price"": //int//
  *""items[].requested_unit_of_measure"": //<unknown>//
  *""items[].requested_weight"": //<unknown>//
  *""items[].unit"": //string//
  *""items[].unit_count"": //int//
  *""items[].unit_price"": //int//
  *""items_price"": //int//
  *""language"": //<unknown>//
  *""loaded_recipe_ids"": //<unknown>//
  *""location_id"": //datetime//
  *""locker_code"": //<unknown>//
  *""log"": //array//
  *""log[].date"": //datetime//
  *""log[].text"": //string//
  *""log[].type"": //string//
  *""log[].user"": //string//
  *""manual_receipt_ids"": //<unknown>//
  *""misc.address"": //<unknown>//
  *""misc.client_name"": //string//
  *""misc.client_phone"": //<unknown>//
  *""misc.pay_method"": //string//
  *""misc.pay_status"": //string//
  *""mobile_calls"": //array//
  *""next_day_email_should_send"": //boolean//
  *""next_day_sms_should_send"": //boolean//
  *""offers_applied"": //array//
  *""offers_discount"": //array//
  *""operator_id"": //<unknown>//
  *""operator_tasks"": //map//
  *""order_note"": //string//
  *""packer_id"": //string//
  *""partner_id"": //<unknown>//
  *""payment_currency"": //<unknown>//
  *""payment_method"": //string//
  *""payment_status"": //string//
  *""picker_communication_type"": //<unknown>//
  *""picker_id"": //string//
  *""picking_method"": //string//
  *""picking_sessions"": //array[string]//
  *""platform_details"": //string//
  *""predicted_arrival_time"": //<unknown>//
  *""predicted_boxes_volume"": //<unknown>//
  *""printing_status"": //string//
  *""priority"": //int//
  *""problem_positions_action"": //<unknown>//
  *""processed_by_worker"": //array//
  *""ps_status"": //string//
  *""pup_id"": //int//
  *""ready_email_sent"": //boolean//
  *""ready_email_sent_time"": //<unknown>//
  *""ready_sms_sent"": //boolean//
  *""ready_sms_sent_time"": //<unknown>//
  *""returned_items_price"": //int//
  *""returns_type"": //<unknown>//
  *""route_number"": //string//
  *""scheduled_to_cancel"": //boolean//
  *""secret"": //string//
  *""sent_to_osr_time"": //datetime//
  *""sent_to_queue"": //boolean//
  *""served"": //datetime//
  *""services_fee.base.comment"": //string//
  *""services_fee.base.value"": //int//
  *""shift_number"": //int//
  *""shoppingsite_id"": //string//
  *""source"": //<unknown>//
  *""stage_by_datetime"": //datetime//
  *""status"": //string//
  *""stop_number"": //int//
  *""store_id"": //<unknown>//
  *""tax"": //int//
  *""totes_unstaged"": //boolean//
  *""totes_unstaged_time"": //datetime//
  *""totes_unstaging_error"": //boolean//
  *""totes_unstaging_error_reason"": //string//
  *""totes_unstaging_error_time"": //<unknown>//
}

@enduml