auth-service:
  helm_chart_version: 22-02-03.169-hotfix.0
bifrost:
  helm_chart_version: 22-02-23.120
cartonization:
  helm_chart_version: 22-03-07.76
decanting-service:
  helm_chart_version: 22-03-08.197
distiller:
  image: 22-02-28.366
  helm_chart_version: 22-03-09.195
ims:
  image: 22-01-14.102
  helm_chart_version: 22-01-14.204
integration:
  helm_chart_version: 22-02-16.980
isps:
  helm_chart_version: 22-02-18.143-hotfix.0
oms:
  helm_chart_version: 22-03-09.411-hotfix.3
osr-emulator:
  helm_chart_version: 22-03-07.173
pickerman:
  helm_chart_version: 22-03-07.113
platform:
  helm_chart_version: 22-03-09.467-hotfix.2
service-catalog:
  helm_chart_version: 22-02-18.232
