auth-service:
  helm_chart_version: 23-03-17.219
bifrost:
  helm_chart_version: 23-03-29.150
cartonization:
  helm_chart_version: 23-03-14.105
decanting-service:
  helm_chart_version: 23-04-01.27
distiller:
  image: 23-03-20.218.1
  helm_chart_version: 23-03-30.133.1
ims:
  image: 23-03-28.14
  helm_chart_version: 23-03-30.268
integration:
  helm_chart_version: 23-03-01.65
platform:
  helm_chart_version: 23-03-29.687
service-catalog:
  helm_chart_version: 23-03-17.273
