auth-service:
  helm_chart_version: 23-01-17.212
bifrost:
  helm_chart_version: 23-01-24.145
cartonization:
  helm_chart_version: 23-01-20.103
decanting-service:
  helm_chart_version: 23-01-18.5
distiller:
  image: 23-01-19.28.1
  helm_chart_version: 23-01-19.9.1
ims:
  image: 23-01-18.5
  helm_chart_version: 23-01-18.261
integration:
  helm_chart_version: 23-01-20.15
isps:
  helm_chart_version: 23-01-25.178
oms:
  helm_chart_version: 23-01-25.522
osr-emulator:
  helm_chart_version: 23-01-25.284
platform:
  helm_chart_version: 23-01-25.659
service-catalog:
  helm_chart_version: 23-01-20.264
