@startuml
hide stereotype
hide circle
!include ../../../../style/default.iuml

package "webhooks_spanner" {
  !include webhooks_spanner_DATABASECHANGELOG.puml
  !include webhooks_spanner_DATABASECHANGELOGLOCK.puml
  !include webhooks_spanner_delivery_history.puml
  !include webhooks_spanner_event_types.puml
  !include webhooks_spanner_webhook_events.puml
  !include webhooks_spanner_webhooks.puml
}
"**webhook_events**" -- "**event_types**"
"**webhook_events**" -- "**webhooks**"

@enduml