@startuml
hide circle
!include ../../../../style/default.iuml

entity "**events**" [[bigquery_sftp_events.puml]] {
  --
  *""id"": //string//
  *""parent_id"": //string//
  *""run_id"": //string//
  *""status"": //string//
  *""type"": //string//
  *""data"": //string//
  *""created_ts"": //timestamp [partitioned]//
}

@enduml