@startuml
hide circle
!include ../../../../style/default.iuml

entity "**camel_messageprocessed**" [[rint-etl_camel_messageprocessed.puml]] {
  --
  *""createdat"": //timestamp with time zone//
  *""messageid"": //text//
  *""processorname"": //character varying(255)//
}

@enduml