@startuml
hide circle
!include ../../../../style/default.iuml

entity "**qrtz_locks**" [[sinfonietta_qrtz_locks.puml]] {
  + ""lock_name"": //character varying(40) [PK]//
  + ""sched_name"": //character varying(120) [PK]//
  --
}

@enduml