@startuml
hide stereotype
hide circle
!include ../../../../style/default.iuml

package "" {
  entity "**label-manager-sites**" [[_label-manager-sites.puml]] {}
}

hide empty fields
hide empty methods

@enduml