auth-service:
  helm_chart_version: 23-07-26.228
bifrost:
  helm_chart_version: 23-07-07.153
cartonization:
  helm_chart_version: 23-07-29.109
decanting-service:
  helm_chart_version: 23-08-28.266
distiller:
  image: 23-08-23.251.1
  helm_chart_version: 23-08-23.194.1
ims:
  image: 23-07-28.47
  helm_chart_version: 23-07-28.277
integration:
  helm_chart_version: 23-06-01.119
platform:
  helm_chart_version: 23-08-21.710
service-catalog:
  helm_chart_version: 23-08-21.278
