auth-service:
  helm_chart_version: 23-07-26.228
bifrost:
  helm_chart_version: 23-09-01.154
cartonization:
  helm_chart_version: 23-07-29.109
decanting-service:
  helm_chart_version: 23-09-19.314
distiller:
  image: 23-08-23.251.1
  helm_chart_version: 23-08-23.194.1
ims:
  image: 23-09-12.54
  helm_chart_version: 23-09-12.279
integration:
  helm_chart_version: 23-09-12.242
platform:
  helm_chart_version: 23-09-20.715
service-catalog:
  helm_chart_version: 23-08-21.278
