@startuml
hide stereotype
hide circle
!include ../../../../style/default.iuml

package "adattatore-oro" {
  !include adattatore-oro_camel_messageprocessed.puml
  !include adattatore-oro_gold_shell_pid.puml
  !include adattatore-oro_qrtz_blob_triggers.puml
  !include adattatore-oro_qrtz_calendars.puml
  !include adattatore-oro_qrtz_cron_triggers.puml
  !include adattatore-oro_qrtz_fired_triggers.puml
  !include adattatore-oro_qrtz_job_details.puml
  !include adattatore-oro_qrtz_locks.puml
  !include adattatore-oro_qrtz_paused_trigger_grps.puml
  !include adattatore-oro_qrtz_scheduler_state.puml
  !include adattatore-oro_qrtz_simple_triggers.puml
  !include adattatore-oro_qrtz_simprop_triggers.puml
  !include adattatore-oro_qrtz_triggers.puml
  !include adattatore-oro_ragtime_migrations.puml
}
"**qrtz_blob_triggers**" -- "**qrtz_triggers**"
"**qrtz_cron_triggers**" -- "**qrtz_triggers**"
"**qrtz_simple_triggers**" -- "**qrtz_triggers**"
"**qrtz_simprop_triggers**" -- "**qrtz_triggers**"
"**qrtz_triggers**" -- "**qrtz_job_details**"

@enduml