@startuml
hide circle
!include ../../../../style/default.iuml

entity "**camel_messageprocessed**" [[tom-gold-integration_camel_messageprocessed.puml]] {
  --
  *""createdat"": //timestamp with time zone//
  *""messageid"": //character varying(100)//
  *""processorname"": //character varying(255)//
}

@enduml