@startuml
hide stereotype
hide circle
!include ../../../../style/default.iuml

package "ondemand_firestore" {
  entity "**users_audit**" [[ondemand_firestore_users_audit.puml]] {}
}

hide empty fields
hide empty methods

@enduml