auth-service:
  helm_chart_version: 21-12-20.166-hotfix.0
bifrost:
  helm_chart_version: 21-12-08.113-hotfix.0
cartonization:
  helm_chart_version: 21-12-21.73
decanting-service:
  helm_chart_version: 22-01-12.323
distiller:
  image: 22-01-05.348-hotfix.1
  helm_chart_version: 22-01-05.169-hotfix.1
ims:
  image: 22-01-10.99
  helm_chart_version: 22-01-10.200
integration:
  helm_chart_version: 21-12-23.875-hotfix.907
isps:
  helm_chart_version: 22-01-11.140
oms:
  helm_chart_version: 21-12-23.394-hotfix.0
osr-emulator:
  helm_chart_version: 22-01-06.170
pickerman:
  helm_chart_version: 22-01-20.101
platform:
  helm_chart_version: 22-01-11.428
service-catalog:
  helm_chart_version: 21-12-20.230
