retailer_specific:
  SERVICE_WORKER_TOKEN: VEtpejhVU2VvMFdrN1BPb3JtU2J1VFRaMmt4cDBlZEVkNE9FVHk2NjNNY3EwVHRjbTRoSDVDRlhVUmZsd1piWW9salltZUxZRkpuUUlOY2VvSTU=
  PRINTNODE_USER: NU1SMDNyOXNtdVpiUlpIaG1FcjR5SG9fZ1dvd3ZmWmlrMWU3WTl2TmZrSQ==