auth-service:
  helm_chart_version: 22-08-10.196-hotfix.0
bifrost:
  helm_chart_version: 22-05-27.130-hotfix.0
cartonization:
  helm_chart_version: 22-07-29.91-hotfix.0
decanting-service:
  helm_chart_version: 22-08-11.283-hotfix.284
distiller:
  image: 22-08-19.399
  helm_chart_version: 22-08-19.239
ims:
  image: 22-08-11.185
  helm_chart_version: 22-08-11.243
integration:
  helm_chart_version: 22-08-25.1317
isps:
  helm_chart_version: 22-07-21.160-hotfix.0
oms:
  helm_chart_version: 22-08-23.466
osr-emulator:
  helm_chart_version: 22-08-19.216
pickerman:
  helm_chart_version: 22-07-27.136
platform:
  helm_chart_version: 22-08-18.581
service-catalog:
  helm_chart_version: 22-07-04.243
