auth-service:
  helm_chart_version: 23-10-20.236
bifrost:
  helm_chart_version: 23-11-10.165
cartonization:
  helm_chart_version: 23-10-25.117
decanting-service:
  helm_chart_version: 23-11-22.545
distiller:
  image: 23-10-18.266.1
  helm_chart_version: 23-10-18.203.1
ims:
  image: 23-09-25.65
  helm_chart_version: 23-10-20.283
integration:
  helm_chart_version: 23-11-01.328
platform:
  helm_chart_version: 23-11-07.730
service-catalog:
  helm_chart_version: 23-10-20.282
