auth-service:
  helm_chart_version: 23-04-17.222
bifrost:
  helm_chart_version: 23-04-11.151
cartonization:
  helm_chart_version: 23-04-13.107
decanting-service:
  helm_chart_version: 23-04-12.31
distiller:
  image: 23-04-13.238.1
  helm_chart_version: 23-04-13.138.1
ims:
  image: 23-04-13.27
  helm_chart_version: 23-04-13.270
integration:
  helm_chart_version: 23-03-01.65
platform:
  helm_chart_version: 23-03-29.687-hotfix.2
service-catalog:
  helm_chart_version: 23-03-17.273
