auth-service:
  helm_chart_version: 22-12-20.209
bifrost:
  helm_chart_version: 22-12-20.141
cartonization:
  helm_chart_version: 22-10-26.96-hotfix.0
decanting-service:
  helm_chart_version: 22-12-15.314
distiller:
  image: 22-12-22.438
  helm_chart_version: 22-12-22.303
ims:
  image: 22-12-12.219
  helm_chart_version: 22-12-12.255
integration:
  helm_chart_version: 22-12-27.1432
isps:
  helm_chart_version: 22-11-25.172-hotfix.0
oms:
  helm_chart_version: 22-12-29.513
osr-emulator:
  helm_chart_version: 22-12-29.265
platform:
  helm_chart_version: 22-12-19.643
service-catalog:
  helm_chart_version: 22-12-21.250
