auth-service:
  helm_chart_version: 23-01-17.212
bifrost:
  helm_chart_version: 23-01-24.145
cartonization:
  helm_chart_version: 23-02-07.104
decanting-service:
  helm_chart_version: 23-01-18.5
distiller:
  image: 23-02-07.102.1
  helm_chart_version: 23-02-07.35.1
ims:
  image: 23-01-18.5
  helm_chart_version: 23-01-18.261
integration:
  helm_chart_version: 23-01-20.15
oms:
  helm_chart_version: 23-02-06.528
osr-emulator:
  helm_chart_version: 23-02-03.289
platform:
  helm_chart_version: 23-02-10.667
service-catalog:
  helm_chart_version: 23-01-30.266
