retailer_specific:
  SERVICE_WORKER_TOKEN: QU1qU3hFaFRESEw1NjdwZ29yN1N4RWhUREhMNzl1Nzl1ZDNNalN4aFRESEw3QTNURVQ5dWQzTWpTeGhnNXRFaERIalN4
  PRINTNODE_USER: amRMVTRoalMyYll6bHI1X2VseTFuYWpaLWZHLTBEajRselpLbU5hMUVUOA==
