auth-service:
  helm_chart_version: 23-07-26.228
bifrost:
  helm_chart_version: 23-07-07.153
cartonization:
  helm_chart_version: 23-07-29.109
decanting-service:
  helm_chart_version: 23-08-01.201
distiller:
  image: 23-06-26.249.1
  helm_chart_version: 23-08-09.186.1
ims:
  image: 23-07-28.47
  helm_chart_version: 23-07-28.277
integration:
  helm_chart_version: 23-06-01.119
platform:
  helm_chart_version: 23-07-26.704
service-catalog:
  helm_chart_version: 23-04-20.277
