auth-service:
  helm_chart_version: 24-01-24.242
bifrost:
  helm_chart_version: 24-02-06.175
cartonization:
  helm_chart_version: 24-02-05.119
decanting-service:
  helm_chart_version: 24-02-05.619
distiller:
  image: 24-01-23.302.1
  helm_chart_version: 24-01-24.240.1
ims:
  image: 24-01-30.80
  helm_chart_version: 24-01-30.291
integration:
  helm_chart_version: 24-01-02.464
osr-emulator:
  helm_chart_version: 24-02-01.324
platform:
  helm_chart_version: 24-02-07.754
service-catalog:
  helm_chart_version: 24-01-23.289
