# This YAML file defines a GitHub Actions workflow named "Run Tests".
# The workflow is triggered when a push event occurs in the repository.
# It is responsible for running tests on the codebase.

name: Run Tests

on:
  push:
    branches:
      - master
    paths:
      - '**/basic_calculator.py'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        pytest src/tests/test_calculator.py
